Fix issues with docker restart and redeploy of peer

diff --git a/jobs/peer/templates/post-deploy.erb b/jobs/peer/templates/post-deploy.erb
--- a/jobs/peer/templates/post-deploy.erb
+++ b/jobs/peer/templates/post-deploy.erb
@@ -3,6 +3,12 @@
 export PATH=$PATH:/var/vcap/packages/docker/bin
 
 NAME=hyperledger/fabric-baseimage
+docker inspect $NAME:latest 2>&1 > /dev/null
+if [ "$?" == "0" ]; then
+   echo "$NAME:latest already exists"
+   exit 0
+fi
+
 RELEASE=`uname -m`-<%= p("peer.chaincode.baseimage_release") %>
 DOCKERHUB_NAME=$NAME:$RELEASE
 
@@ -17,16 +23,16 @@ else
     docker pull $DOCKERHUB_NAME
     docker inspect $DOCKERHUB_NAME 2>&1 > /dev/null
     if [ "$?" == "0" ]; then
-	echo "BUILD-CACHE: Success!"
-	BASENAME=$DOCKERHUB_NAME
+      echo "BUILD-CACHE: Success!"
+      BASENAME=$DOCKERHUB_NAME
     else
-	echo "BUILD-CACHE: WARNING - Build-cache unavailable, attempting local build"
-	(cd $FABRIC_SRC_DIR/images/base && make docker DOCKER_TAG=localbuild)
-	if [ "$?" != "0" ]; then
-            echo "ERROR: Build-cache could not be compiled locally"
-            exit -1
-	fi
-	BASENAME=$NAME:localbuild
+      echo "BUILD-CACHE: WARNING - Build-cache unavailable, attempting local build"
+      (cd $FABRIC_SRC_DIR/images/base && make docker DOCKER_TAG=localbuild)
+      if [ "$?" != "0" ]; then
+        echo "ERROR: Build-cache could not be compiled locally"
+        exit -1
+      fi
+      BASENAME=$NAME:localbuild
     fi
 fi
 
